# api2-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api2-deployment
  namespace: exemplo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api2
  template:
    metadata:
      labels:
        app: api2
    spec:
      containers:
        - name: api2-container
          image: api2:local
          ports:
            - containerPort: 3000
