# api2-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api2-service
  namespace: exemplo-namespace
spec:
  selector:
    app: api2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
